# docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit/
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
tone_instructions: ''
reviews:
  profile: chill
  poem: false
  review_status: false
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  auto_review:
    enabled: true
    drafts: true
