// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import femaleFirstnames from './femaleFirstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import maleFirstnames from './maleFirstnames.json' with { type: 'json' }
import wikipedia from './wikipedia.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-fi': commonWords,
  'femaleFirstnames-fi': femaleFirstnames,
  'lastnames-fi': lastnames,
  'maleFirstnames-fi': maleFirstnames,
  'wikipedia-fi': wikipedia,
  ...wordSequences,
}

export { dictionary, translations }
