// This file is auto generated by data-scripts/_helpers/runtime.ts
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wikipedia from './wikipedia.json'
import translations from './translations'

const dictionary = {
  'firstnames-ar': firstnames,
  'lastnames-ar': lastnames,
  'wikipedia-ar': wikipedia,
}

export { dictionary, translations }
