// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import translations from './translations'

const dictionary = {
  'commonWords-ar': commonWords,
  'firstnames-ar': firstnames,
  'lastnames-ar': lastnames,
}

export { dictionary, translations }
