// This file is auto generated by data-scripts/_helpers/runtime.ts
import firstnames from './firstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = { 'firstnames-ar': firstnames, 'lastnames-ar': lastnames }

export { dictionary, translations }
