// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import names from './names.json' with { type: 'json' }
import wikipedia from './wikipedia.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-id': commonWords,
  'names-id': names,
  'wikipedia-id': wikipedia,
  ...wordSequences,
}

export { dictionary, translations }
