// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import femaleFirstnames from './femaleFirstnames.json'
import lastnames from './lastnames.json'
import maleFirstnames from './maleFirstnames.json'
import translations from './translations'

const dictionary = {
  'commonWords-da-dk': commonWords,
  'femaleFirstnames-da-dk': femaleFirstnames,
  'lastnames-da-dk': lastnames,
  'maleFirstnames-da-dk': maleFirstnames,
}

export { dictionary, translations }
