// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import femaleFirstnames from './femaleFirstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import maleFirstnames from './maleFirstnames.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-da-dk': commonWords,
  'femaleFirstnames-da-dk': femaleFirstnames,
  'lastnames-da-dk': lastnames,
  'maleFirstnames-da-dk': maleFirstnames,
  ...wordSequences,
}

export { dictionary, translations }
