// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wikipedia from './wikipedia.json'
import translations from './translations'

const dictionary = {
  'commonWords-es-es': commonWords,
  'firstnames-es-es': firstnames,
  'lastnames-es-es': lastnames,
  'wikipedia-es-es': wikipedia,
}

export { dictionary, translations }
