// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wordSequences from './wordSequences.json'
import translations from './translations'

const dictionary = {
  'commonWords-ko': commonWords,
  'firstnames-ko': firstnames,
  'lastnames-ko': lastnames,
  ...wordSequences,
}

export { dictionary, translations }
