// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import firstnames from './firstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import wikipedia from './wikipedia.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-de': commonWords,
  'firstnames-de': firstnames,
  'lastnames-de': lastnames,
  'wikipedia-de': wikipedia,
  ...wordSequences,
}

export { dictionary, translations }
