// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wikipedia from './wikipedia.json'
import wordSequences from './wordSequences.json'
import translations from './translations'

const dictionary = {
  'commonWords-zh': commonWords,
  'firstnames-zh': firstnames,
  'lastnames-zh': lastnames,
  'wikipedia-zh': wikipedia,
}

export { dictionary, translations, wordSequences }
