// This file is auto generated by data-scripts/_helpers/runtime.ts
import tempAdjacencyGraphs from './adjacencyGraphs.json' with { type: 'json' }
import diceware from './diceware.json' with { type: 'json' }
import passwords from './passwords.json' with { type: 'json' }

const dictionary = {
  'diceware-common': diceware,
  'passwords-common': passwords,
}

// reinit the variable because the typescript compile will otherwise just reexport the json file which will break as it's a json file
const adjacencyGraphs = tempAdjacencyGraphs
export { dictionary, adjacencyGraphs }
