// This file is auto generated by data-scripts/_helpers/runtime.ts
import adjacencyGraphs from './adjacencyGraphs.json'
import diceware from './diceware.json'
import passwords from './passwords.json'

const dictionary = {
  'diceware-common': diceware,
  'passwords-common': passwords,
}

export { dictionary, adjacencyGraphs }
