// This file is auto generated by data-scripts/_helpers/runtime.ts
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import commonWords from './commonWords.json'
import translations from './translations'
import wikipedia from './wikipedia.json'

const dictionary = {
  'commonWords-ku': commonWords,
  'firstNames-ku': firstnames,
  'lastNames-ku': lastnames,
  'wikipedia-ku': wikipedia,
}

export { dictionary, translations }
