// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wikipedia from './wikipedia.json'
import translations from './translations'

const dictionary = {
  'commonWords-cs': commonWords,
  'firstnames-cs': firstnames,
  'lastnames-cs': lastnames,
  'wikipedia-cs': wikipedia,
}

export { dictionary, translations }
