// This file is auto generated by data-scripts/_helpers/runtime.ts
import boysFirstnames from './boysFirstnames.json' with { type: 'json' }
import commonWords from './commonWords.json' with { type: 'json' }
import girlsFirstnames from './girlsFirstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import wikipedia from './wikipedia.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'boysFirstnames-nl-be': boysFirstnames,
  'commonWords-nl-be': commonWords,
  'girlsFirstnames-nl-be': girlsFirstnames,
  'lastnames-nl-be': lastnames,
  'wikipedia-nl-be': wikipedia,
  ...wordSequences,
}

export { dictionary, translations }
