// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import firstnames from './firstnames.json' with { type: 'json' }
import lastnames from './lastnames.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-ru': commonWords,
  'firstnames-ru': firstnames,
  'lastnames-ru': lastnames,
}

export { dictionary, translations }
