export default [
  {
    calcTime: 0,
    password: '1q2w3e4r5t',
    guesses: 364,
    guessesLog10: 2.5611013836490555,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 9,
        token: '1q2w3e4r5t',
        matchedWord: '1q2w3e4r5t',
        rank: 363,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 363,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 363,
        guessesLog10: 2.559906625036112,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 13104,
      onlineNoThrottlingXPerSecond: 36.4,
      offlineSlowHashingXPerSecond: 0.0364,
      offlineFastHashingXPerSecond: 3.64e-8,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '4 hours',
      onlineNoThrottlingXPerSecond: '36 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 4,
      onlineNoThrottlingXPerSecond: 36,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: '1Q2w3e4r5t',
    guesses: 727,
    guessesLog10: 2.8615344108590377,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 9,
        token: '1Q2w3e4r5t',
        matchedWord: '1q2w3e4r5t',
        rank: 363,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 363,
        uppercaseVariations: 2,
        l33tVariations: 1,
        guesses: 726,
        guessesLog10: 2.8609366207000932,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 26172,
      onlineNoThrottlingXPerSecond: 72.7,
      offlineSlowHashingXPerSecond: 0.0727,
      offlineFastHashingXPerSecond: 7.27e-8,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '7 hours',
      onlineNoThrottlingXPerSecond: '1 minute',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 7,
      onlineNoThrottlingXPerSecond: 1,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: '1q2w3e4r5T',
    guesses: 727,
    guessesLog10: 2.8615344108590377,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 9,
        token: '1q2w3e4r5T',
        matchedWord: '1q2w3e4r5t',
        rank: 363,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 363,
        uppercaseVariations: 2,
        l33tVariations: 1,
        guesses: 726,
        guessesLog10: 2.8609366207000932,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 26172,
      onlineNoThrottlingXPerSecond: 72.7,
      offlineSlowHashingXPerSecond: 0.0727,
      offlineFastHashingXPerSecond: 7.27e-8,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '7 hours',
      onlineNoThrottlingXPerSecond: '1 minute',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 7,
      onlineNoThrottlingXPerSecond: 1,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: 'abcdefg123',
    guesses: 15000,
    guessesLog10: 4.176091259055681,
    sequence: [
      {
        pattern: 'sequence',
        i: 0,
        j: 6,
        token: 'abcdefg',
        sequenceName: 'lower',
        sequenceSpace: 26,
        ascending: true,
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
      {
        pattern: 'sequence',
        i: 7,
        j: 9,
        token: '123',
        sequenceName: 'digits',
        sequenceSpace: 10,
        ascending: true,
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 540000,
      onlineNoThrottlingXPerSecond: 1500,
      offlineSlowHashingXPerSecond: 1.5,
      offlineFastHashingXPerSecond: 0.0000015,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '6 days',
      onlineNoThrottlingXPerSecond: '25 minutes',
      offlineSlowHashingXPerSecond: '2 seconds',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 6,
      onlineNoThrottlingXPerSecond: 25,
      offlineSlowHashingXPerSecond: 2,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'Common character sequences like "abc" are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Avoid common character sequences.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'TESTERINO',
    guesses: 2486000,
    guessesLog10: 6.395501124305626,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 5,
        token: 'TESTER',
        matchedWord: 'tester',
        rank: 619,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 619,
        uppercaseVariations: 2,
        l33tVariations: 1,
        guesses: 1238,
        guessesLog10: 3.092720644684099,
      },
      {
        pattern: 'bruteforce',
        token: 'INO',
        i: 6,
        j: 8,
        guesses: 1000,
        guessesLog10: 2.9999999999999996,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 89496000,
      onlineNoThrottlingXPerSecond: 248600,
      offlineSlowHashingXPerSecond: 248.6,
      offlineFastHashingXPerSecond: 0.0002486,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '3 years',
      onlineNoThrottlingXPerSecond: '3 days',
      offlineSlowHashingXPerSecond: '4 minutes',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 3,
      onlineNoThrottlingXPerSecond: 3,
      offlineSlowHashingXPerSecond: 4,
      offlineFastHashingXPerSecond: null,
    },
    score: 2,
    feedback: {
      warning: 'This is similar to a commonly used password.',
      suggestions: [
        'Add more words that are less common.',
        'Capitalize some, but not all letters.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'aaaaaaa',
    guesses: 85,
    guessesLog10: 1.9294189257142926,
    sequence: [
      {
        pattern: 'repeat',
        i: 0,
        j: 6,
        token: 'aaaaaaa',
        baseToken: 'a',
        baseGuesses: 12,
        repeatCount: 7,
        guesses: 84,
        guessesLog10: 1.9242792860618814,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 3060,
      onlineNoThrottlingXPerSecond: 8.5,
      offlineSlowHashingXPerSecond: 0.0085,
      offlineFastHashingXPerSecond: 8.5e-9,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '51 minutes',
      onlineNoThrottlingXPerSecond: '9 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 51,
      onlineNoThrottlingXPerSecond: 9,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'Repeated characters like "aaa" are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Avoid repeated words and characters.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'Daniel',
    guesses: 109,
    guessesLog10: 2.0374264979406234,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 5,
        token: 'Daniel',
        matchedWord: 'daniel',
        rank: 54,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 54,
        uppercaseVariations: 2,
        l33tVariations: 1,
        guesses: 108,
        guessesLog10: 2.0334237554869494,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 3924,
      onlineNoThrottlingXPerSecond: 10.9,
      offlineSlowHashingXPerSecond: 0.0109,
      offlineFastHashingXPerSecond: 1.09e-8,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '1 hour',
      onlineNoThrottlingXPerSecond: '11 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 1,
      onlineNoThrottlingXPerSecond: 11,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a frequently used password.',
      suggestions: [
        'Add more words that are less common.',
        'Capitalize more than the first letter.',
      ],
    },
  },
  {
    calcTime: 0,
    password: '1234qwer',
    guesses: 105,
    guessesLog10: 2.021189299069938,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 7,
        token: '1234qwer',
        matchedWord: '1234qwer',
        rank: 104,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 104,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 104,
        guessesLog10: 2.0170333392987803,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 3780,
      onlineNoThrottlingXPerSecond: 10.5,
      offlineSlowHashingXPerSecond: 0.0105,
      offlineFastHashingXPerSecond: 1.05e-8,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '1 hour',
      onlineNoThrottlingXPerSecond: '11 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 1,
      onlineNoThrottlingXPerSecond: 11,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: '1234qwe',
    guesses: 2978,
    guessesLog10: 3.473924693416157,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 6,
        token: '1234qwe',
        matchedWord: '1234qwe',
        rank: 2977,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 2977,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 2977,
        guessesLog10: 3.4737788346467244,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 107208,
      onlineNoThrottlingXPerSecond: 297.8,
      offlineSlowHashingXPerSecond: 0.2978,
      offlineFastHashingXPerSecond: 2.978e-7,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '1 day',
      onlineNoThrottlingXPerSecond: '5 minutes',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 1,
      onlineNoThrottlingXPerSecond: 5,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'This is a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: '1234qwert',
    guesses: 12288,
    guessesLog10: 4.089481202687437,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 7,
        token: '1234qwer',
        matchedWord: '1234qwer',
        rank: 104,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 104,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 104,
        guessesLog10: 2.0170333392987803,
      },
      {
        pattern: 'bruteforce',
        token: 't',
        i: 8,
        j: 8,
        guesses: 11,
        guessesLog10: 1.041392685158225,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 442368,
      onlineNoThrottlingXPerSecond: 1228.8,
      offlineSlowHashingXPerSecond: 1.2288,
      offlineFastHashingXPerSecond: 0.0000012288,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '5 days',
      onlineNoThrottlingXPerSecond: '20 minutes',
      offlineSlowHashingXPerSecond: '1 second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 5,
      onlineNoThrottlingXPerSecond: 20,
      offlineSlowHashingXPerSecond: 1,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'This is similar to a commonly used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: 'password',
    guesses: 3,
    guessesLog10: 0.4771212547196623,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 7,
        token: 'password',
        matchedWord: 'password',
        rank: 2,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: false,
        baseGuesses: 2,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 2,
        guessesLog10: 0.30102999566398114,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 108,
      onlineNoThrottlingXPerSecond: 0.3,
      offlineSlowHashingXPerSecond: 0.0003,
      offlineFastHashingXPerSecond: 3e-10,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '2 minutes',
      onlineNoThrottlingXPerSecond: 'less than a second',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 2,
      onlineNoThrottlingXPerSecond: null,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is a heavily used password.',
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: '2010abc',
    guesses: 15000,
    guessesLog10: 4.176091259055681,
    sequence: [
      {
        pattern: 'regex',
        token: '2010',
        i: 0,
        j: 3,
        regexName: 'recentYear',
        regexMatch: ['2010'],
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
      {
        pattern: 'sequence',
        i: 4,
        j: 6,
        token: 'abc',
        sequenceName: 'lower',
        sequenceSpace: 26,
        ascending: true,
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 540000,
      onlineNoThrottlingXPerSecond: 1500,
      offlineSlowHashingXPerSecond: 1.5,
      offlineFastHashingXPerSecond: 0.0000015,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '6 days',
      onlineNoThrottlingXPerSecond: '25 minutes',
      offlineSlowHashingXPerSecond: '2 seconds',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 6,
      onlineNoThrottlingXPerSecond: 25,
      offlineSlowHashingXPerSecond: 2,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'Recent years are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Avoid recent years.',
        'Avoid years that are associated with you.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'abcabcabcabc',
    guesses: 53,
    guessesLog10: 1.724275869600789,
    sequence: [
      {
        pattern: 'repeat',
        i: 0,
        j: 11,
        token: 'abcabcabcabc',
        baseToken: 'abc',
        baseGuesses: 13,
        repeatCount: 4,
        guesses: 52,
        guessesLog10: 1.716003343634799,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 1908,
      onlineNoThrottlingXPerSecond: 5.3,
      offlineSlowHashingXPerSecond: 0.0053,
      offlineFastHashingXPerSecond: 5.3e-9,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '32 minutes',
      onlineNoThrottlingXPerSecond: '5 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 32,
      onlineNoThrottlingXPerSecond: 5,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning:
        'Repeated character patterns like "abcabcabc" are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Avoid repeated words and characters.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'qwer',
    guesses: 1297,
    guessesLog10: 3.1129399760840797,
    sequence: [
      {
        pattern: 'spatial',
        i: 0,
        j: 3,
        token: 'qwer',
        graph: 'qwerty',
        turns: 1,
        shiftedCount: 0,
        guesses: 1296,
        guessesLog10: 3.112605001534574,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 46692,
      onlineNoThrottlingXPerSecond: 129.7,
      offlineSlowHashingXPerSecond: 0.1297,
      offlineFastHashingXPerSecond: 1.297e-7,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '13 hours',
      onlineNoThrottlingXPerSecond: '2 minutes',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 13,
      onlineNoThrottlingXPerSecond: 2,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'Straight rows of keys on your keyboard are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Use longer keyboard patterns and change typing direction multiple times.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'P4$$w0rd',
    guesses: 33,
    guessesLog10: 1.5185139398778873,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 7,
        token: 'P4$$w0rd',
        matchedWord: 'password',
        rank: 2,
        dictionaryName: 'passwords',
        reversed: false,
        l33t: true,
        subs: [
          { letter: 'a', substitution: '4' },
          { letter: 's', substitution: '$' },
          { letter: 'o', substitution: '0' },
        ],
        subDisplay: '4 -> a, $ -> s, 0 -> o',
        baseGuesses: 2,
        uppercaseVariations: 2,
        l33tVariations: 8,
        guesses: 32,
        guessesLog10: 1.5051499783199058,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 1188,
      onlineNoThrottlingXPerSecond: 3.3,
      offlineSlowHashingXPerSecond: 0.0033,
      offlineFastHashingXPerSecond: 3.3e-9,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '20 minutes',
      onlineNoThrottlingXPerSecond: '3 seconds',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 20,
      onlineNoThrottlingXPerSecond: 3,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: 'This is similar to a commonly used password.',
      suggestions: [
        'Add more words that are less common.',
        'Capitalize more than the first letter.',
        "Avoid predictable letter substitutions like '@' for 'a'.",
      ],
    },
  },
  {
    calcTime: 0,
    password: 'aA!1',
    guesses: 10001,
    guessesLog10: 4.000043427276863,
    sequence: [
      {
        pattern: 'bruteforce',
        token: 'aA!1',
        i: 0,
        j: 3,
        guesses: 10000,
        guessesLog10: 4,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 360036,
      onlineNoThrottlingXPerSecond: 1000.1,
      offlineSlowHashingXPerSecond: 1.0001,
      offlineFastHashingXPerSecond: 0.0000010001,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '4 days',
      onlineNoThrottlingXPerSecond: '17 minutes',
      offlineSlowHashingXPerSecond: '1 second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 4,
      onlineNoThrottlingXPerSecond: 17,
      offlineSlowHashingXPerSecond: 1,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: null,
      suggestions: ['Add more words that are less common.'],
    },
  },
  {
    calcTime: 0,
    password: 'dgo9dsghasdoghi8/!&IT%§(ihsdhf8o7o',
    guesses: 2.34e33,
    guessesLog10: 33.36921585741014,
    sequence: [
      {
        pattern: 'bruteforce',
        token: 'dgo9dsg',
        i: 0,
        j: 6,
        guesses: 10000000,
        guessesLog10: 7,
      },
      {
        pattern: 'dictionary',
        i: 7,
        j: 9,
        token: 'has',
        matchedWord: 'has',
        rank: 24,
        dictionaryName: 'wikipedia-en',
        reversed: false,
        l33t: false,
        baseGuesses: 24,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
      {
        pattern: 'dictionary',
        i: 10,
        j: 11,
        token: 'do',
        matchedWord: 'do',
        rank: 22,
        dictionaryName: 'commonWords-en',
        reversed: false,
        l33t: false,
        baseGuesses: 22,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 50,
        guessesLog10: 1.6989700043360185,
      },
      {
        pattern: 'sequence',
        i: 12,
        j: 14,
        token: 'ghi',
        sequenceName: 'lower',
        sequenceSpace: 26,
        ascending: true,
        guesses: 78,
        guessesLog10: 1.8920946026904801,
      },
      {
        pattern: 'bruteforce',
        token: '8/!&IT%§(ihsdhf8o7o',
        i: 15,
        j: 33,
        guesses: 10000000000000000000,
        guessesLog10: 19,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 8.424e34,
      onlineNoThrottlingXPerSecond: 2.34e32,
      offlineSlowHashingXPerSecond: 2.34e29,
      offlineFastHashingXPerSecond: 2.34e23,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: 'centuries',
      onlineNoThrottlingXPerSecond: 'centuries',
      offlineSlowHashingXPerSecond: 'centuries',
      offlineFastHashingXPerSecond: 'centuries',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: null,
      onlineNoThrottlingXPerSecond: null,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 4,
    feedback: { warning: null, suggestions: [] },
  },
  {
    calcTime: 0,
    password: 'AZERYT',
    guesses: 538000,
    guessesLog10: 5.730782275666389,
    sequence: [
      {
        pattern: 'spatial',
        i: 0,
        j: 3,
        token: 'AZER',
        graph: 'azerty',
        turns: 1,
        shiftedCount: 4,
        guesses: 2640,
        guessesLog10: 3.421603926869831,
      },
      {
        pattern: 'bruteforce',
        token: 'YT',
        i: 4,
        j: 5,
        guesses: 100,
        guessesLog10: 2,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 19368000,
      onlineNoThrottlingXPerSecond: 53800,
      offlineSlowHashingXPerSecond: 53.8,
      offlineFastHashingXPerSecond: 0.0000538,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '7 months',
      onlineNoThrottlingXPerSecond: '15 hours',
      offlineSlowHashingXPerSecond: '54 seconds',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 7,
      onlineNoThrottlingXPerSecond: 15,
      offlineSlowHashingXPerSecond: 54,
      offlineFastHashingXPerSecond: null,
    },
    score: 1,
    feedback: {
      warning: 'Straight rows of keys on your keyboard are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Use longer keyboard patterns and change typing direction multiple times.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'zxcftzuio',
    guesses: 12790064,
    guessesLog10: 7.106872717643415,
    sequence: [
      {
        pattern: 'bruteforce',
        token: 'z',
        i: 0,
        j: 0,
        guesses: 11,
        guessesLog10: 1.041392685158225,
      },
      {
        pattern: 'spatial',
        i: 1,
        j: 8,
        token: 'xcftzuio',
        graph: 'qwertz',
        turns: 3,
        shiftedCount: 0,
        guesses: 580912,
        guessesLog10: 5.7641103478653735,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 460442304,
      onlineNoThrottlingXPerSecond: 1279006.4,
      offlineSlowHashingXPerSecond: 1279.0064,
      offlineFastHashingXPerSecond: 0.0012790064,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '14 years',
      onlineNoThrottlingXPerSecond: '15 days',
      offlineSlowHashingXPerSecond: '21 minutes',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 14,
      onlineNoThrottlingXPerSecond: 15,
      offlineSlowHashingXPerSecond: 21,
      offlineFastHashingXPerSecond: null,
    },
    score: 2,
    feedback: {
      warning: 'Short keyboard patterns are easy to guess.',
      suggestions: [
        'Add more words that are less common.',
        'Use longer keyboard patterns and change typing direction multiple times.',
      ],
    },
  },
  {
    calcTime: 0,
    password: 'buy by beer',
    guesses: 1301200000,
    guessesLog10: 9.114344054609814,
    sequence: [
      {
        pattern: 'bruteforce',
        token: 'bu',
        i: 0,
        j: 1,
        guesses: 100,
        guessesLog10: 2,
      },
      {
        pattern: 'repeat',
        i: 2,
        j: 7,
        token: 'y by b',
        baseToken: 'y b',
        baseGuesses: 1001,
        repeatCount: 2,
        guesses: 2002,
        guessesLog10: 3.3014640731432996,
      },
      {
        pattern: 'bruteforce',
        token: 'eer',
        i: 8,
        j: 10,
        guesses: 1000,
        guessesLog10: 2.9999999999999996,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 46843200000,
      onlineNoThrottlingXPerSecond: 130120000,
      offlineSlowHashingXPerSecond: 130120,
      offlineFastHashingXPerSecond: 0.13012,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: 'centuries',
      onlineNoThrottlingXPerSecond: '4 years',
      offlineSlowHashingXPerSecond: '2 days',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: null,
      onlineNoThrottlingXPerSecond: 4,
      offlineSlowHashingXPerSecond: 2,
      offlineFastHashingXPerSecond: null,
    },
    score: 3,
    feedback: { warning: null, suggestions: [] },
  },
  {
    calcTime: 0,
    password: 'horse stable battery',
    guesses: 1128013300000000,
    guessesLog10: 15.052314220287887,
    sequence: [
      {
        pattern: 'dictionary',
        i: 0,
        j: 4,
        token: 'horse',
        matchedWord: 'horse',
        rank: 862,
        dictionaryName: 'commonWords-en',
        reversed: false,
        l33t: false,
        baseGuesses: 862,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 862,
        guessesLog10: 2.9355072658247123,
      },
      {
        pattern: 'bruteforce',
        token: ' stable ',
        i: 5,
        j: 12,
        guesses: 100000000,
        guessesLog10: 8,
      },
      {
        pattern: 'dictionary',
        i: 13,
        j: 19,
        token: 'battery',
        matchedWord: 'battery',
        rank: 2181,
        dictionaryName: 'wikipedia-en',
        reversed: false,
        l33t: false,
        baseGuesses: 2181,
        uppercaseVariations: 1,
        l33tVariations: 1,
        guesses: 2181,
        guessesLog10: 3.3386556655787,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 40608478800000000,
      onlineNoThrottlingXPerSecond: 112801330000000,
      offlineSlowHashingXPerSecond: 112801330000,
      offlineFastHashingXPerSecond: 112801.33,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: 'centuries',
      onlineNoThrottlingXPerSecond: 'centuries',
      offlineSlowHashingXPerSecond: 'centuries',
      offlineFastHashingXPerSecond: '1 day',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: null,
      onlineNoThrottlingXPerSecond: null,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: 1,
    },
    score: 4,
    feedback: { warning: null, suggestions: [] },
  },
  {
    calcTime: 0,
    password: 'a65a54cf-eadb-4f7c-893c-9d4a6f81f8c2',
    guesses: 9.999999999999999e35,
    guessesLog10: 35.99999999999999,
    sequence: [
      {
        pattern: 'bruteforce',
        token: 'a65a54cf-eadb-4f7c-893c-9d4a6f81f8c2',
        i: 0,
        j: 35,
        guesses: 9.999999999999999e35,
        guessesLog10: 35.99999999999999,
      },
    ],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 3.6e37,
      onlineNoThrottlingXPerSecond: 1e35,
      offlineSlowHashingXPerSecond: 9.999999999999999e31,
      offlineFastHashingXPerSecond: 9.999999999999999e25,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: 'centuries',
      onlineNoThrottlingXPerSecond: 'centuries',
      offlineSlowHashingXPerSecond: 'centuries',
      offlineFastHashingXPerSecond: 'centuries',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: null,
      onlineNoThrottlingXPerSecond: null,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 4,
    feedback: { warning: null, suggestions: [] },
  },
  {
    calcTime: 0,
    password: '',
    guesses: 1,
    guessesLog10: 0,
    sequence: [],
    crackTimesSeconds: {
      onlineThrottlingXPerHour: 36,
      onlineNoThrottlingXPerSecond: 0.1,
      offlineSlowHashingXPerSecond: 0.0001,
      offlineFastHashingXPerSecond: 1e-10,
    },
    crackTimesDisplay: {
      onlineThrottlingXPerHour: '36 seconds',
      onlineNoThrottlingXPerSecond: 'less than a second',
      offlineSlowHashingXPerSecond: 'less than a second',
      offlineFastHashingXPerSecond: 'less than a second',
    },
    crackTimesBase: {
      onlineThrottlingXPerHour: 36,
      onlineNoThrottlingXPerSecond: null,
      offlineSlowHashingXPerSecond: null,
      offlineFastHashingXPerSecond: null,
    },
    score: 0,
    feedback: {
      warning: null,
      suggestions: [
        'Use multiple words, but avoid common phrases.',
        'You can create strong passwords without using symbols, numbers, or uppercase letters.',
      ],
    },
  },
]
