// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import wikipedia from './wikipedia.json'
import wordSequences from './wordSequences.json'
import translations from './translations'

const dictionary = {
  'commonWords-th': commonWords,
  'wikipedia-th': wikipedia,
}

export { dictionary, translations, wordSequences }
