// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import femaleFirstnames from './femaleFirstnames.json'
import femaleLastnames from './femaleLastnames.json'
import maleFirstnames from './maleFirstnames.json'
import maleLastnames from './maleLastnames.json'
import wikipedia from './wikipedia.json'
import translations from './translations'

const dictionary = {
  'commonWords-pl': commonWords,
  'femaleFirstnames-pl': femaleFirstnames,
  'femaleLastnames-pl': femaleLastnames,
  'maleFirstnames-pl': maleFirstnames,
  'maleLastnames-pl': maleLastnames,
  'wikipedia-pl': wikipedia,
}

export { dictionary, translations }
