// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json' with { type: 'json' }
import femaleFirstnames from './femaleFirstnames.json' with { type: 'json' }
import femaleLastnames from './femaleLastnames.json' with { type: 'json' }
import maleFirstnames from './maleFirstnames.json' with { type: 'json' }
import maleLastnames from './maleLastnames.json' with { type: 'json' }
import wikipedia from './wikipedia.json' with { type: 'json' }
import wordSequences from './wordSequences.json' with { type: 'json' }
import translations from './translations.ts'

const dictionary = {
  'commonWords-pl': commonWords,
  'femaleFirstnames-pl': femaleFirstnames,
  'femaleLastnames-pl': femaleLastnames,
  'maleFirstnames-pl': maleFirstnames,
  'maleLastnames-pl': maleLastnames,
  'wikipedia-pl': wikipedia,
  ...wordSequences,
}

export { dictionary, translations }
