// This file is auto generated by data-scripts/_helpers/runtime.ts
import commonWords from './commonWords.json'
import firstnames from './firstnames.json'
import lastnames from './lastnames.json'
import wikipedia from './wikipedia.json'
import translations from './translations'

const dictionary = {
  'commonWords-fr': commonWords,
  'firstnames-fr': firstnames,
  'lastnames-fr': lastnames,
  'wikipedia-fr': wikipedia,
}

export { dictionary, translations }
